[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = -v --tb=short
markers =
    positive: позитивные тесты
    negative: негативные тесты
    auth: тесты авторизации
    news: тесты новостей
    comments: тесты комментариев